
// 登录获取Token
export const UPDATETOKEN = 'UPDATETOKEN'
export const UPDATEDLOCATION = "UPDATEDLOCATION"
export const UPDATEADDRESS = "UPDATEADDRESS"
export const UPDATEUSERINFO = "UPDATEUSERINFO"
export const SETPROID = "SETPROID"
export const SETCURRENTADD = "SETCURRENTADD"
export const SETAGENT = "SETAGENT"
